# bare minimal
name: googlesheet

on:
    push:
      branches:
        - master
    workflow_dispatch:

jobs:
    fetch:
      runs-on: ubuntu-latest
      steps:
        - id: googlesheet_actions
          uses: rjoydip/googlesheet-actions@0.1.1
          with:
            sheet-id: 1OKQWbmX1c728Uk7aERe3zcp1zqcUarSgSDSDkYJro1g
        - id: echo
          uses: actions/github-script@v2
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                console.log(${{steps.googlesheet_actions.outputs.result}})
        - name: test
          run: |
            cat $HOME/data.json
